lable ${EXTLINUX_VENDOR}
	kernel ${EXTLINUX_KERNEL}
	initrd ${EXTLINUX_INITRD}
	append root=${EXTLINUX_ROOTFS} ${EXTLINUX_CMDLINE}
	fdtdir ${EXTLINUX_FDTDIR}
	fdt ${EXTLINUX_FDT}
	fdtoverlay ${EXTLINUX_FDTOVERLAY}
